### PR TITLE
update server licence

### PR DESCRIPTION
**Pull request by philippebn**
make sure to use on distant server and not 127.0.0.1
If it doesn't work, make all *.sh is LF and not Windows file (CRLF).

Enjoy

### CODE REVIEW

**Comment by dingdayu** [comment]
thank you for your support, I checked all *.sh, is LF;

Change the code just changed the port number, just want to find out you can change the default port parameters.

**Comment by philippebn** [comment]
You can change the port number directly from the application jetbrain server
image
and it's specified with parameter "-p"



Remember when you change the port number, you need to changed exposed port in your dockerfile
After that your container are ok.

**Comment by philippebn** [comment]
You can changed after again your exposed port when you launch your container with docker 

Ex: docker run -p 9080:1227....etc

9080 port your machine 
1227 the internal exposed port in container

**Comment by dingdayu** [comment]
yes.

Despite the support "-p", But did not specify, it is recommended to do port switching docker or nginx

**Comment by dingdayu** [comment]
Do you update the JetBrainsLicenseServer_amd64 or JetBrainsLicenseServer_arm ?

**Pull request closed without merging**
